#!/usr/bin/env bash

set -xe

: "${GITHUB_USER?Need a GitHub username}"
: "${GITHUB_REPO?Need a repository name}"
: "${GITHUB_BRANCH?Need a GitHub branch}"

# For pull requests https://help.github.com/articles/checking-out-pull-requests-locally/
if [[ $GITHUB_BRANCH == *PR-[0-9]* ]]; then

  PR_BRANCH_ID=$(echo $GITHUB_BRANCH | cut -f2 -d "-")
  PR_BRANCH="PR-$PR_BRANCH_ID"
  GITHUB_BRANCH=develop
fi

# Clone repo and get inside
if [[ -z "${GITHUB_TOKEN}" ]]; then
  git clone -b "$GITHUB_BRANCH" https://github.com/"$GITHUB_USER"/"$GITHUB_REPO".git /tmp/"$GITHUB_REPO"
else
  git clone -b "$GITHUB_BRANCH" https://"$GITHUB_TOKEN"@github.com/"$GITHUB_USER"/"$GITHUB_REPO".git /tmp/"$GITHUB_REPO"
fi

# Specific action for Pull Requests
if [[ $PR_BRANCH == *PR-[0-9]* ]]; then
  cd /tmp/"$GITHUB_REPO"
  git fetch origin pull/$PR_BRANCH_ID/head:$PR_BRANCH
  git checkout $PR_BRANCH
fi

# Install dependencies and perform tests
npm install
npm test